apiVersion: apps/v1
kind: Deployment
metadata:
  name: starcoin-dag-inspector-deployment
  namespace: starcoin-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: starcoin-dag-inspector
  template:
    metadata:
      labels:
        app: starcoin-dag-inspector
    spec:
      containers:
        - name: react-app
          image: starcoin/starcoin_dag_inspector:v0.0.3
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: starcoin-dag-inspector-service
  namespace: starcoin-client
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      nodePort: 31100
  selector:
    app: starcoin-dag-inspector